// Auto-generated by cbindgen. Do not edit.


#ifndef RUST_CORE_H
#define RUST_CORE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Engine Engine;

typedef struct PlaybackClipInfo {
  char *id;
  char *url;
  uint64_t time_in_clip_ms;
} PlaybackClipInfo;

struct Engine *engine_new(void);

void engine_free(struct Engine *engine);

void engine_add_clip(struct Engine *engine,
                     const char *id,
                     const char *url,
                     uint64_t in_ms,
                     uint64_t out_ms,
                     uintptr_t idx);

void engine_remove_clip(struct Engine *engine, uintptr_t idx);

void engine_cut_clip(struct Engine *engine, uintptr_t idx, uint64_t position);

void engine_update_clip_range(struct Engine *engine,
                              uintptr_t idx,
                              uint64_t in_point,
                              uint64_t out_point);

uintptr_t engine_get_clip_count(const struct Engine *engine);

char *engine_get_clip_id(const struct Engine *engine, uintptr_t idx);

char *engine_get_clip_url(const struct Engine *engine, uintptr_t idx);

uint64_t engine_get_clip_in_point(const struct Engine *engine, uintptr_t idx);

uint64_t engine_get_clip_out_point(const struct Engine *engine, uintptr_t idx);

void engine_play(struct Engine *engine);

void engine_pause(struct Engine *engine);

void engine_seek(struct Engine *engine, uint64_t time_ms);

void engine_tick(struct Engine *engine, uint64_t delta_ms);

uint64_t engine_get_playback_time(const struct Engine *engine);

bool engine_is_playing(const struct Engine *engine);

struct PlaybackClipInfo *engine_get_current_playback_clip_info(const struct Engine *engine);

void free_playback_clip_info(struct PlaybackClipInfo *info);

void free_rust_string(char *ptr);

int32_t add_one(int32_t x);

int32_t multiply_by_two(int32_t x);

int32_t divide_by_two(int32_t x);

/**
 * Serializes the current project to a JSON string.
 * The caller is responsible for freeing the returned string with `free_rust_string`.
 */
char *engine_get_project_as_json(struct Engine *engine);

/**
 * Loads a project from a JSON string. This resets the dirty flag.
 */
bool engine_load_project_from_json(struct Engine *engine, const char *json_data);

/**
 * Sets the current file path in the engine. Swift calls this after a successful save/open.
 */
void engine_set_current_file_path(struct Engine *engine, const char *file_path);

/**
 * Marks the current project as saved by clearing the dirty flag.
 */
void engine_mark_as_saved(struct Engine *engine);

bool engine_new_project(struct Engine *engine, const char *name);

char *engine_get_project_name(const struct Engine *engine);

char *engine_get_current_file_path(const struct Engine *engine);

bool engine_has_unsaved_changes(const struct Engine *engine);

#endif  /* RUST_CORE_H */
