// Auto-generated by cbindgen. Do not edit.


#ifndef RUST_CORE_H
#define RUST_CORE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int32_t add_one(int32_t x);

int32_t multiply_by_two(int32_t x);

int32_t divide_by_two(int32_t x);

#endif  /* RUST_CORE_H */
